//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yakovlev_41_size
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoint
    {
        public int PickUpPointID { get; set; }
        public string PickUpIndex { get; set; }
        public string PickUpCity { get; set; }
        public string PickUpStreet { get; set; }
        public int PickUpHouse { get; set; }
        public string PickUpAddress { get
            {
                return PickUpIndex +" "+ PickUpCity + " " + PickUpStreet + " " + PickUpHouse;
            }
        }
    }
}
